// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioSite.Data;

#nullable disable

namespace PortfolioSite.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260413145342_AddAdminAdsenseConnection")]
    partial class AddAdminAdsenseConnection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PortfolioSite.Data.AdminAdsenseConnectionRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AccountDisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ConnectedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RefreshTokenCiphertext")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("admin_adsense_connections", (string)null);
                });

            modelBuilder.Entity("PortfolioSite.Data.PortfolioCareerItemRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Highlights")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PortfolioContentId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioContentId");

                    b.ToTable("portfolio_career_items", (string)null);
                });

            modelBuilder.Entity("PortfolioSite.Data.PortfolioContactLinkRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Href")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PortfolioContentId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioContentId");

                    b.ToTable("portfolio_contact_links", (string)null);
                });

            modelBuilder.Entity("PortfolioSite.Data.PortfolioContentRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CareerSectionHeading")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CareerSectionIntro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactHeading")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactNote")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FaviconSrc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FooterRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HeroEyebrow")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HeroImageAlt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HeroImageSrc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HeroTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PersonalSectionHeading")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PersonalSectionIntro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileCertifications")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileCertificationsHeading")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileFocusHeading")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileFocusItems")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileSectionBody")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileSectionHeading")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileSectionIntro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileSectionLead")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileShortName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileSummary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileTags")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SiteTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SkillsSectionHeading")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SkillsSectionIntro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WorksSectionHeading")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WorksSectionIntro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("portfolio_contents", (string)null);
                });

            modelBuilder.Entity("PortfolioSite.Data.PortfolioHighlightRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PortfolioContentId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioContentId");

                    b.ToTable("portfolio_profile_highlights", (string)null);
                });

            modelBuilder.Entity("PortfolioSite.Data.PortfolioPersonalItemRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DetailBody")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DetailSummary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageAlt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageSrc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Points")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PortfolioContentId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Stack")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioContentId");

                    b.ToTable("portfolio_personal_items", (string)null);
                });

            modelBuilder.Entity("PortfolioSite.Data.PortfolioSkillCategoryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PortfolioContentId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioContentId");

                    b.ToTable("portfolio_skill_categories", (string)null);
                });

            modelBuilder.Entity("PortfolioSite.Data.PortfolioSkillItemRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PortfolioSkillCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioSkillCategoryId");

                    b.ToTable("portfolio_skill_items", (string)null);
                });

            modelBuilder.Entity("PortfolioSite.Data.PortfolioWorkItemRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Outcomes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PortfolioContentId")
                        .HasColumnType("int");

                    b.Property<string>("Responsibilities")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Stack")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioContentId");

                    b.ToTable("portfolio_work_items", (string)null);
                });

            modelBuilder.Entity("PortfolioSite.Models.Identity.AdminUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PortfolioSite.Models.Identity.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PortfolioSite.Models.Identity.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortfolioSite.Models.Identity.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PortfolioSite.Models.Identity.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortfolioSite.Data.PortfolioCareerItemRecord", b =>
                {
                    b.HasOne("PortfolioSite.Data.PortfolioContentRecord", "PortfolioContent")
                        .WithMany("CareerItems")
                        .HasForeignKey("PortfolioContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortfolioContent");
                });

            modelBuilder.Entity("PortfolioSite.Data.PortfolioContactLinkRecord", b =>
                {
                    b.HasOne("PortfolioSite.Data.PortfolioContentRecord", "PortfolioContent")
                        .WithMany("ContactLinks")
                        .HasForeignKey("PortfolioContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortfolioContent");
                });

            modelBuilder.Entity("PortfolioSite.Data.PortfolioHighlightRecord", b =>
                {
                    b.HasOne("PortfolioSite.Data.PortfolioContentRecord", "PortfolioContent")
                        .WithMany("ProfileHighlights")
                        .HasForeignKey("PortfolioContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortfolioContent");
                });

            modelBuilder.Entity("PortfolioSite.Data.PortfolioPersonalItemRecord", b =>
                {
                    b.HasOne("PortfolioSite.Data.PortfolioContentRecord", "PortfolioContent")
                        .WithMany("PersonalItems")
                        .HasForeignKey("PortfolioContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortfolioContent");
                });

            modelBuilder.Entity("PortfolioSite.Data.PortfolioSkillCategoryRecord", b =>
                {
                    b.HasOne("PortfolioSite.Data.PortfolioContentRecord", "PortfolioContent")
                        .WithMany("SkillCategories")
                        .HasForeignKey("PortfolioContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortfolioContent");
                });

            modelBuilder.Entity("PortfolioSite.Data.PortfolioSkillItemRecord", b =>
                {
                    b.HasOne("PortfolioSite.Data.PortfolioSkillCategoryRecord", "PortfolioSkillCategory")
                        .WithMany("Items")
                        .HasForeignKey("PortfolioSkillCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortfolioSkillCategory");
                });

            modelBuilder.Entity("PortfolioSite.Data.PortfolioWorkItemRecord", b =>
                {
                    b.HasOne("PortfolioSite.Data.PortfolioContentRecord", "PortfolioContent")
                        .WithMany("WorkItems")
                        .HasForeignKey("PortfolioContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortfolioContent");
                });

            modelBuilder.Entity("PortfolioSite.Data.PortfolioContentRecord", b =>
                {
                    b.Navigation("CareerItems");

                    b.Navigation("ContactLinks");

                    b.Navigation("PersonalItems");

                    b.Navigation("ProfileHighlights");

                    b.Navigation("SkillCategories");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("PortfolioSite.Data.PortfolioSkillCategoryRecord", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
