#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  bash scripts/create-runtime-env.sh [output_path]
  ./scripts/create-runtime-env.sh [output_path]

Creates a shell/systemd-compatible env file for runtime settings.
Use this for shared runtime or server deployment, not for local development secrets.

Examples:
  bash scripts/create-runtime-env.sh
  bash scripts/create-runtime-env.sh /etc/portfolio-site/portfolio-site.env

Prompted values:
  ASPNETCORE_ENVIRONMENT
    Usually Production on server
  ASPNETCORE_URLS
    Usually http://127.0.0.1:5000 behind nginx
  ConnectionStrings__PortfolioDatabase
    MySQL connection string
  Configure admin credentials?
    yes: prompt for AdminAccount__LoginId and AdminAccount__Password
    no: write Admin / 0000 automatically
  ReverseProxy__TrustAllProxies
    Usually false on same-host nginx reverse proxy

Enter raw values without surrounding quotes.

The generated file can be used in either of these ways:
  set -a; . ./.secrets/portfolio-site.env; set +a
  EnvironmentFile=/etc/portfolio-site/portfolio-site.env
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ $# -gt 1 ]]; then
  usage >&2
  exit 1
fi

output_path="${1:-.secrets/portfolio-site.env}"

prompt_with_default() {
  local message="$1"
  local default_value="$2"
  local input=""

  read -r -p "${message} [${default_value}]: " input
  if [[ -z "$input" ]]; then
    printf '%s' "$default_value"
    return
  fi

  printf '%s' "$input"
}

prompt_required() {
  local message="$1"
  local input=""

  while true; do
    read -r -p "${message}: " input
    if [[ -n "$input" ]]; then
      printf '%s' "$input"
      return
    fi

    echo "Value is required." >&2
  done
}

prompt_secret_required() {
  local message="$1"
  local input=""

  while true; do
    read -r -s -p "${message}: " input
    printf '\n' >&2
    if [[ -n "$input" ]]; then
      printf '%s' "$input"
      return
    fi

    echo "Value is required." >&2
  done
}

prompt_yes_no() {
  local message="$1"
  local default_value="$2"
  local input=""
  local normalized=""

  while true; do
    read -r -p "${message} [${default_value}]: " input
    normalized="${input:-$default_value}"
    normalized="$(printf '%s' "$normalized" | tr '[:upper:]' '[:lower:]')"

    if [[ "$normalized" == "yes" || "$normalized" == "no" ]]; then
      printf '%s' "$normalized"
      return
    fi

    echo "Please enter yes or no." >&2
  done
}

quote_for_env_file() {
  local value="$1"

  value=${value//\\/\\\\}
  value=${value//\"/\\\"}
  value=${value//\$/\\\$}
  value=${value//\`/\\\`}

  printf '"%s"' "$value"
}

write_entry() {
  local key="$1"
  local value="$2"

  printf '%s=%s\n' "$key" "$(quote_for_env_file "$value")"
}

if [[ -f "$output_path" ]]; then
  overwrite="$(prompt_with_default "Output file already exists. Overwrite? (yes/no)" "no")"
  if [[ "$overwrite" != "yes" ]]; then
    echo "Cancelled." >&2
    exit 1
  fi
fi

aspnetcore_environment="${PORTFOLIO_ASPNETCORE_ENVIRONMENT:-}"
aspnetcore_urls="${PORTFOLIO_ASPNETCORE_URLS:-}"
db_connection="${PORTFOLIO_DATABASE_CONNECTION:-}"
admin_login_id="${PORTFOLIO_ADMIN_LOGIN_ID:-}"
admin_password="${PORTFOLIO_ADMIN_PASSWORD:-}"
trust_all_proxies="${PORTFOLIO_TRUST_ALL_PROXIES:-}"

if [[ -z "$aspnetcore_environment" ]]; then
  aspnetcore_environment="$(prompt_with_default "ASPNETCORE_ENVIRONMENT" "Production")"
fi

if [[ -z "$aspnetcore_urls" ]]; then
  aspnetcore_urls="$(prompt_with_default "ASPNETCORE_URLS" "http://127.0.0.1:5000")"
fi

if [[ -z "$db_connection" ]]; then
  db_connection="$(prompt_required "ConnectionStrings__PortfolioDatabase")"
fi

if [[ -z "$admin_login_id" && -z "$admin_password" ]]; then
  configure_admin_credentials="$(prompt_yes_no "Configure admin credentials? (yes/no)" "no")"
  if [[ "$configure_admin_credentials" == "yes" ]]; then
    admin_login_id="$(prompt_required "AdminAccount__LoginId")"
    admin_password="$(prompt_secret_required "AdminAccount__Password")"
  else
    admin_login_id="Admin"
    admin_password="0000"
  fi
else
  if [[ -z "$admin_login_id" ]]; then
    admin_login_id="Admin"
  fi

  if [[ -z "$admin_password" ]]; then
    admin_password="0000"
  fi
fi

if [[ -z "$trust_all_proxies" ]]; then
  trust_all_proxies="$(prompt_with_default "ReverseProxy__TrustAllProxies" "false")"
fi

mkdir -p "$(dirname "$output_path")"

{
  echo "# Generated by scripts/create-runtime-env.sh"
  echo "# Shell usage: set -a; . \"$output_path\"; set +a"
  echo "# systemd usage: EnvironmentFile=$output_path"
  write_entry "ASPNETCORE_ENVIRONMENT" "$aspnetcore_environment"
  write_entry "ASPNETCORE_URLS" "$aspnetcore_urls"
  write_entry "ConnectionStrings__PortfolioDatabase" "$db_connection"
  write_entry "AdminAccount__LoginId" "$admin_login_id"
  write_entry "AdminAccount__Password" "$admin_password"
  write_entry "ReverseProxy__TrustAllProxies" "$trust_all_proxies"
} > "$output_path"

chmod 600 "$output_path"

echo "Wrote runtime env file: $output_path"
echo "Local shell: set -a; . \"$output_path\"; set +a"
echo "systemd: add EnvironmentFile=$output_path"
